### ISSUE TITLE
Broke my Server

### ISSUE THREAD

**Issue by AlphaZetta** [Sven65/Slabbo#1]
lol its a plagiarised rip off delete this or thirtyvirus will nuke you even harder

**Comment by ajgeiss0702** [comment]
Welcome to the real world with other people in it. Competition is a thing and always has been. If he can't deal with it, maybe this isn't the thing for him.

**Comment by Sven65** [comment]
Not a bug, also see https://www.spigotmc.org/threads/how-to-take-down-a-generic-carbon-copy-plugin.451138/.

**Comment by AlphaZetta** [comment]
> Welcome to the real world with other people in it. Competition is a thing and always has been. If he can't deal with it, maybe this isn't the thing for him.

It's not competition, it's a blatant rip-off made by someone who was mad that Thirty couldn't update to 1.16 because it broke the plugin.

**Comment by ajgeiss0702** [comment]
It’s someone who got tired of waiting so they re-made the whole thing on their own. 

In thirtyvirus’s video he even says he got the idea from a server, so it’s not his idea. Yes, he added guis and stuff but this guy added 1.16 support on top of it being built from the ground up himself.
