### ISSUE TITLE
Feature Idea: GPFlags only build in claims

### ISSUE THREAD

**Issue by arkD** [Sven65/Slabbo#10]
this may seem silly, but I couldn't find anywhere that you use a stick to create a shop. I had to look up uShops to figure it out. Once I knew what I was looking for a quick ctrl+f showed it at the top under what is Slabbo! I think the reason I couldn't find it was because I didn't expect it there and was looking in permissions/commands and even features trying to find it.
Suggestion? repeat it somewhere it makes sense like:
slabbo.create - Lets a player create shops 'using a stick'

It surprises me how many negative reviews this mod has, I can tell you put a lot of good work into this, I hope you do not feel discouraged.

Here is my feature request:
It would be nice to control where a user could create shops, aka only inside world guards or grief prevention claims ( I prefer the latter). maybe a config option?
even better would be if we could add a flag using GPFlags to allow admins to determine if a player's claim can have a shop in it.

I could try to take a crack at it with a pull request, but it has been a decade since I have programmed in java and will only do so if you do not think you might implement this reasonably without my help. (please give me a timeline)

Many Thanks,
~Ark

**Comment by Sven65** [comment]
Hi there! Feel free to submit a pull request for the GPFlags! I'll have you know that I've got a pretty small amount of experience with GP, let alone the flags 😅

As for the stick repetition, I'll see what I can do!

**Comment by arkD** [comment]
Alright. It would be helpful so I will clone the repo and give it a try. Again, it has been a decade since I used java, but there is personal motivation for my server, so I will see what I can do.
