### ISSUE TITLE
[Feature request] Support for decimal points (like cents)

### ISSUE THREAD

**Issue by 0x5c** [Sven65/Slabbo#17]
Some economy providers (like EssentialsX) support decimal points in amounts of currency.
This would be great in Slabbo, to allow for items that aren't worth much to be sold in quantity of one.

Current support in Slabbo: "5$"
This feature: "4.50$"

**Comment by AdimoPL** [comment]
Absolutely, for our server shop we want to have a very calculated economy and as such decimal points would be a great addition!

+1

**Comment by Sven65** [comment]
I looked through the code, and this shouldn't be that hard to do, even with migrations.

It should just be a simple case of saving a double to `shops.yml` instead of an int.

**Comment by AdimoUK** [comment]
Hi Sven, Have you got any updates on when we could expect this to be implemented?

**Comment by Sven65** [comment]
As of now, I unfortunately can't give an estimate due to other projects taking precedence. I'll try to get it in soon enough though!

**Comment by Sven65** [comment]
I had a look at it again, and there's some more decisions that need to be made before I can go ahead and implement it, such as the display of prices, i.e, should it be `$4.00` or just `$4`, should that be a config option etc.

Once I've ironed those out, I'll get to work on the decimal feature.

Thanks for your patience!

**Comment by 0x5c** [comment]
> I had a look at it again, and there's some more decisions that need to be made before I can go ahead and implement it, such as the display of prices, i.e, should it be $4.00 or just $4, should that be a config option etc.

I think that should definitely be a configuration option (or language string, anything server owners can set easily), that way the plugin works nicely with existing currency symbols and formats for servers that don't use $n (USD format)

**Comment by Sven65** [comment]
Hi! Apologies for taking an extreme amount of time in getting back to this.

I've *finally* gotten around to implementing this, and it'll be included in the next release.

In order to enable it, you need to set the `allowCents`  configuration key to `true`
