### ISSUE TITLE
Error while removing slabbo shop without linked chest

### ISSUE THREAD

**Issue by lennert05** [Sven65/Slabbo#33]
# Bug details

if you remove your slabbo shop without a chest linked you get a nullpointerexception error

**To Reproduce**
1. make a slabbo shop
2. configure it without linking a chest
3. destroy the shop

**Expected behavior**
the shop that is destroyed without an error in the console log

**Screenshots**
![image](https://user-images.githubusercontent.com/34865816/111679935-f9bacf80-8821-11eb-9bd2-e5afba3db452.png)

# Runtime Configuration

**Slabbo Version:** 1.0.24

**Server Software:** Purpur 
**buildnr:** 1022

**Server Version:** 1.16.5

**Comment by Sven65** [comment]
Unable to reproduce this issue with Spigot.
