### ISSUE TITLE
Duplication glitch! [IMPORTANT]

### ISSUE THREAD

**Issue by MartinClementz** [Sven65/Slabbo#36]
# Super simple duplication glitch

**This bug allows the player to duplicate items when modifying their own shop. For example, can the player put 64 stone in their shop, then change the item being sold to a diamond. This makes all the stone turn into diamonds, and the player can take out 64 diamonds from their shop.**

**To Reproduce**
1. Make a Slabbo-shop
2. Fill it up with stone/dirt/leaves/etc.
3. Fill the shop up 64 of that block (the amount you want to duplicate)
4. Modify the shop to a different item, then click confirm.
5. Take out all the items form the shop
6. You now have 64 of the item

**Expected behavior**
I expect the shop to delete all the items in the shop, or give it to the player. I can also imagine that the shop wont allow me to change the block, when there are items in the shop.
 

**Screenshots**

# Runtime Configuration

**Slabbo Version:** 1.0.24

**Server Software:** Spigot

**Server Version:** What to write her? Spigot_latest_1.16.5

# Other details

**Additional context**

**Comment by Sven65** [comment]
Thanks! I'll get it fixed ASAP.

**Comment by MartinClementz** [comment]
Tanks! Appreciate the quick response. I would also use this opportunity to say that this plugin is stupidly simple to use. There is practically no learning curve. Love it!

**Comment by Sven65** [comment]
Thanks for the support!
