### ISSUE TITLE
move the hovering items by using fishing rod.

### ISSUE THREAD

**Issue by Dreeam-qwq** [Sven65/Slabbo#40]
# Bug details

**Describe the bug**
the hovering items of the shops can be moved by players.
but, the hovering items need to stay above the Slabbo

**To Reproduce**
1. create a shop with hovering item
2. use a fishing rod to hook the item
3. the hovering item move to other place

**Expected behavior**
just using a fishing rod, to move the hovering item anywhere you want.
The hovering item needs to stay above the Slabbo!

**Screenshots**
![Picture.jpg](https://i.loli.net/2021/08/03/dpbMq9gO7aNRXyw.jpg)

# Runtime Configuration

**Slabbo Version:** 1.0.28

**Server Software:** Paper

**Server Version:** 1.14.4

# Other details

**Additional context**

**Comment by tindybell** [comment]
You can move it with a water bukket as well

**Comment by MaHl111** [comment]
> You can move it with a water bukket as well

#48
