### ISSUE TITLE
Error: Could not pass event PlayerInteractEvent to Slabbo v1.0.47

### ISSUE THREAD

**Issue by DaddyPig991** [Sven65/Slabbo#75]
When I start a server I get this error: 
[message.txt](https://github.com/Sven65/Slabbo/files/13199248/message.txt)
Then I try to reload the plugin and it gives me this error:
[message (1).txt](https://github.com/Sven65/Slabbo/files/13199254/message.1.txt)

I had the same error with the v1.0.46.  So I updated it to v1.0.47, but the problem stayed.
I thought the problem was the software (Arclight) which is not popular and maybe isn't reliable and so on.
So I created an absolutely new server with the same plugins and mods and it doesn't give me this error.
Maybe I should mention as well that the shops doesn't work in WorldGuard regions or players claimed Lands.

**Comment by Sven65** [comment]
Hi, please rewrite this using the template provided, as I am unable to reproduce the error correctly without all the information.
