### ISSUE TITLE
Could not pass event PlayerInteractEvent to Slabbo v1.0.47

### ISSUE THREAD

**Issue by DaddyPig991** [Sven65/Slabbo#76]
# Bug details

**Describe the bug**
When I start the server I get an error: Could not pass event PlayerInteractEvent to Slabbo v1.0.47
It gives me this error when I reload the plugin as well.
**To Reproduce**
1. I don't even know how

**Expected behavior**
No errors

**Screenshots**
Error message in log.
![image](https://github.com/Sven65/Slabbo/assets/111451749/85beeb4f-eb36-4469-acd9-5a1d0298fc34)

# Runtime Configuration

**Slabbo Version:** 1.0.47

**Server Software:** Arclight

**Server Version:** 1.20.1

# Other details

**Additional context**
The same problem was with v1.0.46
I tried creating a new server with the same plugins and mods and it didn't give me an error somehow.

**Comment by Sven65** [comment]
Which WorldGuard version are you using?

**Comment by ChoiWang** [comment]
> Which WorldGuard version are you using?

I'm a different person from the writer, but I have the same problem.

I am using version 1.0.50 of slabbo and version 7.0.9 of worldguard.

**Comment by ChoiWang** [comment]
> Which WorldGuard version are you using?

I'm a different person from the writer, but I have the same problem.

I am using version 1.0.50 of slabbo and version 7.0.9 of worldguard.

**Comment by Sven65** [comment]
I'm unable to replicate this error, do you have more details on replicating it, especially in newer versions?

**Comment by Sven65** [comment]
No new info for 6 months. Closing.
